### ISSUE TITLE
sirènes PSE03-v1.1.0: ajout commandes

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1846]
https://github.com/pipiche38/Domoticz-Zigate/blob/stable/Classes/IAS.py

**Comment by mickadam29** [comment]
Partant pour des tests si tu veux car j'ai des sirènes PSE03-v1.1.0 dont tu as fais un modèle mais seule l'alarme fonctionne. Il y a possibilité de générer d'autres sons. Les clusters sont connus.  
[Multi Sound Siren PSE03 _ Manualzz.pdf](https://github.com/KiwiHC16/Abeille/files/6057254/Multi.Sound.Siren.PSE03._.Manualzz.pdf)

The Siren from Philio (PSE02) is sold as a multi sound device, but to make it play other sounds it has to receive a NOTIFICATION_REPORT. This report is normally sent out from a sensor such as a PIR or door/window-sensor. That means it's possible to e.g. play a Door Chime sound when a door/window-sensor is opened.
When sending a SWITCH_BINARY_SET (which is the default command that will be sent to this device from TellStick ZNet) will only make it play the default emergency sound.
In order to play other sounds, a NOTIFICATION_REPORT has to be sent out from TellStick - that can be done from a Lua-script.
We've put together a script that can send out the NOTIFICATION_REPORT when a device (or dummy-device) is turned on, it's available here:

https://github.com/telldus/tellstick-lua-examples/blob/master/zwave/Philio/Siren.lua

**Comment by Brugal21** [comment]
Je ne sais pas si c'est possible, mais il y a aussi un flash lumineux qui peut être géré sur cette sirène.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by Brugal21** [comment]
Salut,

Je reviens sur cette alarme, est-il possible de faire fonctionner les commandes pour les autres sons et la gestion du flash lumineux ? Est ce que la doc suffit ou faut-il que l'on fasse quelque chose, récupérer les logs ? A dispo pour aider à avancer sur le sujet.

**Comment by tcharp38** [comment]
Salut @Brugal21 
Toujours interessé ?

**Comment by tcharp38** [comment]
Je clos ce tres vieux sujet.
A reouvrir si ca interesse à nouveau qqn.
